---
title: "Rmarkdown_LM"
author: "Leah Moubadder, Jasmine Aqua, Susan Hoffman"
date: "11/15/2021"
output: pdf_document
---
---
title: "Spatial Epi Project"
author: "Leah Moubadder, Jasmine Aqua, Susan Hoffman"
date: "11/11/2021"
output: 
  pdf_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Objective: 

# Loading packages
```{r load packages}
pacman::p_load(tidyverse, # General data wrangling
raster,
rgdal,
sp,
readxl,
sf, # manage spatial data using simple features
tmap) # mapping of sf or sp data
```


# Loading data
```{r load data}
#outcome data
EJscreen <- read.csv("Data/ej_ga.csv")

#exposure geometry data 
HOLC_map <- readOGR(dsn=path.expand("Data/HRS2020-Shapefiles/HRS2020"),
                            layer="HRS2020")
#exposure attribute data
HOLC_score <- read_excel("Data/Historic Redlining Score 2020.xlsx")
```


# Explore shapefiles (HIDE SECTION BEFORE SUBMISSION)
Source for code below: https://www.neonscience.org/resources/learning-hub/tutorials/dc-open-shapefiles-r
```{r explore}
# view just the class for the shapefile
class(HOLC)

# view just the crs for the shapefile
crs(HOLC)

# view just the extent for the shapefile
extent(HOLC)

# view all metadata at same time
HOLC

# alternate way to view attributes 
HOLC_map@data

# view a summary of metadata & attributes associated with the spatial object
summary(HOLC_map)

#add leading zero
HOLC_score$GEOID20 <- paste0("0", HOLC_score$GEOID20)

#multiple ways to get the same map:
plot(HOLC_map)
tm_shape(HOLC_map) + tm_polygons()

tm_shape(HOLC_map) + tm_polygons("Shape_Leng") 
```

```{r join}


library(tidycensus)
#add census tract
geo_id<-append_geoid(EJscreen, 'tr')

#return number of NA geoids
sum(is.na(geo_id$geoid)) 
#11 NA geoid

```

